{"name": "用户60s内请求登陆多次", "status": "passed", "steps": [{"name": "用户请求登陆", "status": "passed", "start": 1673433452962, "stop": 1673433453591}, {"name": "用户请求登陆", "status": "passed", "start": 1673433453591, "stop": 1673433453983}], "attachments": [{"name": "log", "source": "062946a3-ad1e-44f2-9650-abbae080d07d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_title", "value": "'用户60s内请求登陆多次'"}, {"name": "email", "value": "'15873664025@163.com'"}, {"name": "status_code", "value": "400"}, {"name": "code", "value": "2300000"}], "start": 1673433452961, "stop": 1673433453983, "uuid": "4d5987f3-bd4f-4038-a0b0-e478df3c36f6", "historyId": "c62076f02cd8ecc6b225bc20f4d34dd7", "testCaseId": "ca9ecc23e355d6459a1de431e8469ae7", "fullName": "Testcase.Test_User.test_user_reqmore_fail.Test_create_custodial_account#test_create_account_custodial", "labels": [{"name": "story", "value": "User Connect Fail!"}, {"name": "feature", "value": "Users Fail!"}, {"name": "parentSuite", "value": "Testcase.Test_User"}, {"name": "suite", "value": "test_user_reqmore_fail"}, {"name": "subSuite", "value": "Test_create_custodial_account"}, {"name": "host", "value": "lilongdeMacBook-Pro.local"}, {"name": "thread", "value": "2820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase.Test_User.test_user_reqmore_fail"}]}